CC=gcc -std=c99

all: question1 question4 question5 question8

question1: question1.c
	$(CC) question1.c -o question1

question4: question4.c
	$(CC) question4.c -o question4

question5: question5.c
	$(CC) question5.c -o question5

question8: question8.c
	$(CC) question8.c -o question8

clean:
	rm -f question1 question4 question5 question8


# Required by the assignment

XQTR: question1
	./question1

XQT: question8
	./question8
